package com.adept.api.audit;

public enum AuditAction {
    ACCOUNT_SIGNUP,
    EMAIL_VERIFIED,
    VERIFICATION_EMAIL_REQUESTED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    SESSION_REFRESHED,
    REFRESH_REUSE_DETECTED,
    LOGOUT,
    WORKSPACE_SWITCHED,
    WORKSPACE_CREATED,
    WORKSPACE_UPDATED,
    WORKSPACE_DELETION_REQUESTED,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_REPOSITORIES_UPDATED,
    PROJECT_DELETED
}
