package com.adept.api.common.domain;

public enum ProcessingJobType {
    PROCESS_GITHUB_EVENT, PROCESS_JIRA_EVENT, SYNC_GITHUB_REPOSITORIES,
    BACKFILL_REPOSITORY, SYNC_JIRA_PROJECTS, RENEW_JIRA_WEBHOOK,
    RECALCULATE_METRICS, EVALUATE_ALERTS, DELETE_WORKSPACE
}
